<?php
	$dil["kiralamaKosullari"] = "شروط و أحكام";
	$dil["SSS"] = "أسئلة شائعة";
	$dil["iletisim"] = "اتصل بنا";
	$dil["transfer"] = "نقل شخصي";
	$dil["filomuz"] = "لائحة الاسعار";
	$dil["filomuztolower"] = "لائحة الاسعار";
	$dil["hakkinda"] = "من نحن";
	$dil["anasayfa"] = "منزل";
	$dil["destekverezervasyon"] = "دعم والحجز الخط الساخن";
	$dil["tunhaklarsakli"] = "جميع الحقوق محفوظة.";
	$dil["otokiralama"] = "تأجير سيارات";
	$dil["onlinearackiralama"] = "على الانترنت الحجز السيارات";
	$dil["rezervasyonbilgimetni"] = "يمكنك حجز سيارتك فورا ملء الاستمارة.";
	$dil["alisyeri"] = "المركز الأول";
	$dil["alisyeriseciniz"] = "يرجى تحديد المكان";
	$dil["donusyeri"] = "نهاية الموقف";
	$dil["donusyeriseciniz"] = "يرجى تحديد المكان";
	$dil["alistarihsaat"] = "تاريخ الإستلام / التوقيت";
	$dil["donustarihsaat"] = "تاريخ التسليم / التوقيت";
	$dil["parabirimi"] = "عملة";
	$dil["rezervasyonolustur"] = "إنشاء الحجز";
	$dil["adanasakirpasahavalimani"] = "Adana Sakirpasa مطار";
	$dil["havalimani"] = "مطار";
	$dil["merkezofis"] = "المكتب الرئيسي";
	$dil["ankaraesenbogahavalimani"] = "Ankara Esenboga مطار";
	$dil["kahramanmarashavalimani"] = "Kahramanmaras مطار";
	$dil["merkez"] = "مركز";
	$dil["gunluk"] = "يومي";
	$dil["rezervasyon"] = "حجز";
	$dil["hizlirezervasyon"] = "حجز سريع";
	$dil["hizlirezervasyonbilgi"] = "الحجز من خلال هذا الموقع، يمكنك الحصول على موافقة فورية، ويمكن أن يتم ذلك بسرعة.";
	$dil["merkeziyerler"] = "المواقع المركزية";
	$dil["merkeziyerlerbilgi"] = "يمكنك أن تأخذ سيارتك إلى أقرب مواقع مراكز التسليم ويمكن تسليمها إلى ميز.";
	$dil["ekonomikfiyatlar"] = "أسعار معقولة";
	$dil["ekonomikfiyatlarbilgi"] = "لكل ميزانية، تتوفر أسعار تأجير السيارات الاقتصادية. الجودة وآمنة وتتمتع تجربة خالية من المتاعب.";
	$dil["724canlidestek"] = "7/24 الدعم المباشر";
	$dil["724bilgi"] = "7 أيام 24 ساعة يمكن أن يحصل بجانب الدعم والمعلومات وقتما تشاء. يمكنك العثور على معلومات مفصلة حول أدواتنا.";
	$dil["bazihizmetlerimizvekampanyalar"] = "بعض من خدماتنا والحملات";
	$dil["devaminioku"] = "إقرأ المزيد";
	$dil["ocak"] = "كانون الثاني";
	$dil["subat"] = "فبراير";
	$dil["mart"] = "آذار";
	$dil["nisan"] = "نيسان";
	$dil["mayis"] = "مايو";
	$dil["haziran"] = "يونيو";
	$dil["temmuz"] = "يوليو";
	$dil["agustos"] = "أغسطس";
	$dil["eylul"] = "سبتمبر";
	$dil["ekim"] = "أكتوبر";
	$dil["kasim"] = "تشرين الثاني";
	$dil["aralik"] = "ديسمبر";
	$dil["menu"] = "قائمة طعام";
	$dil["hizmetlerimiz"] = "خدماتنا";
	
	
	$dil["iletisimFormu"] = "نموذج الاتصال";
	$dil["adSoyad"] = "اسمك واسم العائلة الخاص بك";
	$dil["tel"] = "هاتف";
	$dil["eposta"] = "البريد الإلكتروني";
	$dil["konu"] = "الموضوع";
	$dil["mesajiniz"] = "رسالة";
	$dil["gonder"] = "ارسال";
	
	
	$dil["alisbilgileri"] = "معلومات الموقع الأول";
	$dil["donusbilgileri"] = "المعلومات نهاية الموقف";
	$dil["yakitBenzin"] = "بنزين";
	$dil["yakitDizel"] = "ديزل";
	$dil["yakitLPG"] = "غاز البترول المسال";
	$dil["videsDuz"] = "يدويا";
	$dil["videsOtomatik"] = "تلقائي";
	$dil["videsTiptronik"] = "تيبترونيك";
	$dil["gun"] = "يوم";
	$dil["reservasyonbilgilerikaydedildi"] = "تحفظ المعلومات المحفوظة";
	$dil["gecerlitariharaligiseciniz"] = "تحديد نطاق تاريخ صالح.";
	
	$dil["gunlukFiyati"] = "الأسعار اليومية";
	$dil["gunSayisi"] = "عدد اليوم";
	$dil["ekstraUcretler"] = "رسوم إضافية";
	$dil["toplam"] = "مجموع";
	
	$dil["alisyerismall"] = "المركز الأول";
	$dil["donusyerismall"] = "نهاية الموقف";
	$dil["alistarihi"] = "الإيجار تاريخ بدء";
	$dil["donustarihi"] = "عودة التاريخ";
	$dil["alissaati"] = "الإيجار وقت بدء";
	$dil["donussaati"] = "العودة الوقت";
	
	$dil["ekstralar"] = "إضافات";
	$dil["bebekKoltugu"] = "كرسي الطفل";
	$dil["navigasyon"] = "ملاحة";
	$dil["ozelSofor"] = "سائق خاص";
	$dil["karZinciri"] = "سلسلة زلق";
	$dil["ozelSoforLang"] = "سائق خاص (الإنجليزية-ألماني)";
	$dil["ekstraSigorta"] = "اضافية التأمين CDW";
	$dil["istiyorum"] = "أريد";
	$dil["istemiyorum"] = "لا أرغب";
	
	$dil["kisiselBilgileriniz"] = "المعلومات الشخصية الخاصة بك";
	$dil["adSoyad"] = "اسم ولقب";
	$dil["ulke"] = "بلد";
	$dil["havayoluSirketi"] = "شركة الطيران";
	$dil["kalkisHavalimani"] = "من مطار";
	$dil["ucusNo"] = "رقم رحلة طيران";
	$dil["ozelIstekleriniz"] = "طلبات خاصة";
	$dil["odemeTipi"] = "نوع الدفع";
	$dil["nakit"] = "النقدية";
	$dil["krediKarti"] = "بطاقة ائتمان";
	$dil["havaleEFT"] = "نقل";
	$dil["rezervasyonuTamamla"] = "اتمام الحجز";
	$dil["reservasyonBilgileriniGiriniz"] = "أدخل معلومات الحجز";
	
	$dil["varisYeri"] = "المكان المقصود";
	$dil["kisi"] = "شخص";
	$dil["kisiSayisi"] = "عدد شخص";
	$dil["mesafe"] = "مسافه";
	$dil["TransferRezervasyonFormu"] = "Transfer Rezervasyon Formu";
	$dil["RezervasyonTamamlandi"] = "<span style='color: #060;'>تم الانتهاء من الحجز</span><br> <span style='font-size:14px;'>سنعود لكم في أقرب وقت ممكن</span>";
	$dil["islemBasarisiz"] = "<span style='color: #F00;'>فشلت العملية</span><br> <span style='font-size:14px;'>الرجاء معاودة المحاولة في وقت لاحق</span>";
	$dil["mesajIletildi"] = "<span style='color: #060;'>وقام بتسليم الرسالة</span><br> <span style='font-size:14px;'>سنعود لكم في أقرب وقت ممكن</span>";
	$dil["formBosAlanlar"] = "(*) المجالات المشار إليها بعلامة النجمة لا يمكن أن يكون فارغا";
?>