<?php
	$dil["kiralamaKosullari"] = "TERMS & CONDITIONS";
	$dil["SSS"] = "F. A. Q.";
	$dil["iletisim"] = "CONTACT US";
	$dil["transfer"] = "TRANSFERS";
	$dil["filomuz"] = "OUR FLEET";
	$dil["filomuztolower"] = "Our Fleet";
	$dil["hakkinda"] = "ABOUT US";
	$dil["anasayfa"] = "HOME";
	$dil["destekverezervasyon"] = "Support and Booking Hotline";
	$dil["tunhaklarsakli"] = "All Rights Reserved.";
	$dil["otokiralama"] = "Rent A Car";
	$dil["onlinearackiralama"] = "Online Car Reservation";
	$dil["rezervasyonbilgimetni"] = "You can book your car immediately fill out the form.";
	$dil["alisyeri"] = "FIRST POSITION";
	$dil["alisyeriseciniz"] = "Select The First Position";
	$dil["donusyeri"] = "RETURN ADDRESS";
	$dil["donusyeriseciniz"] = "Return Select Location";
	$dil["alistarihsaat"] = "RENTAL START DATE / TIME";
	$dil["donustarihsaat"] = "DATE OF RETURN / TIME";
	$dil["parabirimi"] = "Currency";
	$dil["rezervasyonolustur"] = "Create Reservation";
	$dil["adanasakirpasahavalimani"] = "Adana Þakirpaþa Airport";
	$dil["havalimani"] = "Airport";
	$dil["merkezofis"] = "Center Office";
	$dil["ankaraesenbogahavalimani"] = "Ankara Esenboða Airport";
	$dil["kahramanmarashavalimani"] = "Kahramanmaraþ Airport";
	$dil["merkez"] = "Center";
	$dil["gunluk"] = "Daily";
	$dil["rezervasyon"] = "Reservation";
	$dil["hizlirezervasyon"] = "Instant Booking";
	$dil["hizlirezervasyonbilgi"] = "Your reservation through this website, you can get instant approval and can be done quickly.";
	$dil["merkeziyerler"] = "Central Locations";
	$dil["merkeziyerlerbilgi"] = "You can take your car to the nearest delivery center locations and can deliver.";
	$dil["ekonomikfiyatlar"] = "Affordable Rates";
	$dil["ekonomikfiyatlarbilgi"] = "For every budget, our economic car rental rates are available. Quality, safe and enjoy a hassle-free experience.";
	$dil["724canlidestek"] = "7/24 Live Support";
	$dil["724bilgi"] = "7 Days 24 Hours next can receive support and information whenever you want. You can find detailed information about our tools.";
	$dil["bazihizmetlerimizvekampanyalar"] = "Some services & Campaigns";
	$dil["devaminioku"] = "Read More";
	$dil["ocak"] = "January";
	$dil["subat"] = "February";
	$dil["mart"] = "March";
	$dil["nisan"] = "April";
	$dil["mayis"] = "May";
	$dil["haziran"] = "June";
	$dil["temmuz"] = "July";
	$dil["agustos"] = "August";
	$dil["eylul"] = "September";
	$dil["ekim"] = "October";
	$dil["kasim"] = "November";
	$dil["aralik"] = "December";
	$dil["menu"] = "Menu";
	$dil["hizmetlerimiz"] = "Our Services";
	
	
	$dil["iletisimFormu"] = "Contact Form";
	$dil["adSoyad"] = "Your name and your surname";
	$dil["tel"] = "Telephone";
	$dil["eposta"] = "Email";
	$dil["konu"] = "Topic";
	$dil["mesajiniz"] = "Message";
	$dil["gonder"] = "Submit";
	
	$dil["alisbilgileri"] = "The First Position Info";
	$dil["donusbilgileri"] = "End Position Info";
	$dil["yakitBenzin"] = "Gasoline";
	$dil["yakitDizel"] = "Diesel";
	$dil["yakitLPG"] = "LPG";
	$dil["videsDuz"] = "Manual";
	$dil["videsOtomatik"] = "Automatic";
	$dil["videsTiptronik"] = "Tiptronic";
	$dil["gun"] = "Day";
	$dil["reservasyonbilgilerikaydedildi"] = "Reservation Information Saved";
	$dil["gecerlitariharaligiseciniz"] = "Specify a valid date range.";
	
	$dil["gunlukFiyati"] = "Daily Price";
	$dil["gunSayisi"] = "Number Of The Day";
	$dil["ekstraUcretler"] = "Extra Fees";
	$dil["toplam"] = "Total";
	
	$dil["alisyerismall"] = "First Position";
	$dil["donusyerismall"] = "Return Address";
	$dil["alistarihi"] = "Rental Start Date";
	$dil["donustarihi"] = "Rental Return Date";
	$dil["alissaati"] = "Rental Start Time";
	$dil["donussaati"] = "Rental Return Time";
	
	$dil["ekstralar"] = "Extras";
	$dil["bebekKoltugu"] = "Baby Chair";
	$dil["navigasyon"] = "Navigation";
	$dil["ozelSofor"] = "Private Driver";
	$dil["karZinciri"] = "Skid Shain";
	$dil["ozelSoforLang"] = "Private Driver (English-Deutsche)";
	$dil["ekstraSigorta"] = "Extra Insurance CDW";
	$dil["istiyorum"] = "I Want";
	$dil["istemiyorum"] = "I Do Not Want";
	
	$dil["kisiselBilgileriniz"] = "Your Personal Information";
	$dil["adSoyad"] = "Name and Surname";
	$dil["ulke"] = "Country";
	$dil["havayoluSirketi"] = "Airline Company";
	$dil["kalkisHavalimani"] = "From Airport";
	$dil["ucusNo"] = "Flight Number";
	$dil["ozelIstekleriniz"] = "Special Requests";
	$dil["odemeTipi"] = "Payment Type";
	$dil["nakit"] = "Cash";
	$dil["krediKarti"] = "Credit Card";
	$dil["havaleEFT"] = "Transfer / EFT";
	$dil["rezervasyonuTamamla"] = "Reservation Complete";
	$dil["reservasyonBilgileriniGiriniz"] = "Enter the Reservation Information";
	
	$dil["varisYeri"] = "Destination";
	$dil["kisi"] = "Person";
	$dil["kisiSayisi"] = "Person Number";
	$dil["mesafe"] = "Distance";
	$dil["TransferRezervasyonFormu"] = "Transfer Reservation Form";
	$dil["RezervasyonTamamlandi"] = "<span style='color: #060;'>The booking was completed.</span><br> <span style='font-size:14px;'>We will return to you as soon as possible.</span>";
	$dil["islemBasarisiz"] = "<span style='color: #F00;'>There was a problem.</span><br> <span style='font-size:14px;'>Please try again later.</span>";
	$dil["mesajIletildi"] = "<span style='color: #060;'>The message was transmitted.</span><br><span style='font-size:14px;'>We will return to you as soon as possible.</span>";
	$dil["formBosAlanlar"] = "(*) The areas indicated with an asterisk can not be empty.";
?>